### ISSUE TITLE
READONLY_EXCEPT_TRY_AGAIN is missing in interactive behaviour renderer in Moodle 3.9

### ISSUE THREAD

**Issue by imarichev** [BeteLgis/moodle-qbehaviour_interactive_for_digitalliteracy#2]
In Moodle 3.9 there is no READONLY_EXCEPT_TRY_AGAIN constant in qbehaviour_interactive_renderer class, so qbehaviour_interactive_for_digitalliteracy_renderer->controls(...) fails with exceprion and needs to be ported to newer version.

**Comment by BeteLgis** [comment]
Moodle 3.9.3 support was added.
